spring:
  application:
    name: repository
  datasource:
    url: jdbc:h2:./data/rmbdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;MV_STORE=false;LOCK_TIMEOUT=300000;LOCK_MODE=0
    username: username
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
server:
  port: ${boot.port:9002}
  servlet:
    context-path: /repository
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}:${application.version}
      registryFetchIntervalSeconds: 30
      zone: Main
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: true
    preferSameZoneEureka: true
    filter-only-up-instances: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka.server.url}